#!/usr/bin/env sh

(set -x; node -v;)
(set -x; npm -v;)
(set -x; yarn -v;)

(set -x; brew uninstall --force nvm;)
(set -x; brew uninstall --force n;)
(set -x; brew uninstall --force nodebrew;)
(set -x; brew uninstall --force node-build;)
(set -x; brew uninstall --force nodenv;)
(set -x; brew uninstall --force nodeenv;)
(set -x; brew uninstall --force nave;)
(set -x; brew uninstall --force llnode;)
(set -x; brew uninstall --force node;)
(set -x; brew uninstall --force yarn;)

(set -x; brew prune;)

(set -x; brew doctor &>/dev/null;)

(set -x; brew prune;)


(set -x; node -v;)
(set -x; npm -v;)


(set -x; rm -rf /usr/local/lib/node*;)
(set -x; rm -rf /usr/local/include/node*;)
(set -x; rm -rf ~/local/node*;)
(set -x; rm -rf ~/lib/node*;)
(set -x; rm -rf ~/include/node*;)
(set -x; rm -rf /usr/local/bin/node*;)
(set -x; rm -rf /usr/local/bin/npm*;)
(set -x; rm -rf /usr/local/lib/dtrace/node.d)
(set -x; rm -rf /usr/local/share/man/man1/node*;)
(set -x; rm -rf /usr/local/share/man/man1/npm*;)
(set -x; rm -rf /usr/local/share/man/man2/node*;)
(set -x; rm -rf /usr/local/share/man/man2/npm*;)
(set -x; rm -rf /usr/local/share/man/man3/node*;)
(set -x; rm -rf /usr/local/share/man/man3/npm*;)
(set -x; rm -rf /usr/local/share/man/man4/node*;)
(set -x; rm -rf /usr/local/share/man/man4/npm*;)
(set -x; rm -rf /usr/local/share/man/man5/node*;)
(set -x; rm -rf /usr/local/share/man/man5/npm*;)
(set -x; rm -rf /usr/local/share/man/man6/node*;)
(set -x; rm -rf /usr/local/share/man/man6/npm*;)
(set -x; rm -rf /usr/local/share/man/man7/node*;)
(set -x; rm -rf /usr/local/share/man/man7/npm*;)
(set -x; rm -rf /usr/local/share/man/man8/node*;)
(set -x; rm -rf /usr/local/share/man/man8/npm*;)
(set -x; rm -rf /usr/local/share/man/man9/node*;)
(set -x; rm -rf /usr/local/share/man/man9/npm*;)
(set -x; rm -rf /usr/local/lib/dtrace/node.d;)
(set -x; rm -rf ~/.npm;)
(set -x; rm -rf ~/.yarnrc;)
(set -x; rm -rf ~/.babel.json;)
(set -x; rm -rf ~/node_modules/;)
(set -x; rm -rf ~/.node*;)
(set -x; rm -rf /opt/local/bin/node;)
(set -x; rm -rf /opt/local/include/node;)
(set -x; rm -rf /opt/local/lib/node*;)
(set -x; rm -rf /usr/bin/npm;)
(set -x; rm -rf /usr/local/share/systemtap/tapset/node.stp;)
(set -x; rm -rf /var/db/receipts/org.nodejs.*;)
(set -x; rm -rf ~/.nvm;)
(set -x; rm -rf /usr/local/Cellar/node;)


(set -x; node -v;)

(set -x; npm -v;)

(set -x; yarn -v;)
